name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'  # каждый день в 02:00 UTC
  workflow_dispatch:      # и вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: ./gradlew --no-daemon clean build